name: Link checking CLI
on:
  push:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: update linux packages
        run: sudo apt update
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
         node-version: 'node' # or use 'lts/*' for the latest LTS version
      
      - name: check links 🏗
        run: bash ./assets/scripts/check_links_cli.sh

