name: Link checking CLI
on:
  push:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Install dependencies 🔧
        run: cd ./scripts/check_links_cli.mjs/ && bundle install
      - name: Build HTML frm markdown and check links 🏗
        run: node ./scripts/check_links_cli.msj

