name: Link checking CLI
on:
  push:
    branches:
      - main
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: update linux packages
        run: sudo apt update
      - name: check links 🏗
        run: bash ./scripts/check_links_cli.sh

