name: Lint MDX Files

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Lint MDX files
      run: |
        npx eslint '**/*.mdx' --format json -o eslint-report.json
        if [ -s eslint-report.json ]; then
          cat eslint-report.json
          exit 1
        fi
